import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import Navigation from './components/Layout/Navigation/Navigation'
import Footer from './components/Layout/Footer/Footer'

const rubik = Rubik({
	variable: '--font-rubik',
	weight: ['300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='no'>
			<body className={`${rubik.className} antialiased items-center`}>
				<Navigation />

				<main className='w-full flex flex-col items-center'>
					{children}
				</main>

				<Footer />
			</body>
		</html>
	)
}
